name: sso
services:

  sso-postgres:
    container_name: "sso-postgres"
    image: bitnami/postgresql:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sso_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: sso_db
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: sso_pass
      POSTGRESQL_PORT: 5432
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    restart: on-failure

    volumes:
      - ./db/migration/01_init.up.sql:/docker-entrypoint-initdb.d/init.sql