env: "local"  
tokenTtl: "1h"

sso:
  grpc:  
    port: 44044  
    timeout: 10h

db:
  sqlite:
    storagePath: "db/storage/sso.db"  
    migrationPath: "db/migration"
    migrationTable: "migration"

  postgres:
    host: 'localhost'
    port: 5432
    user: 'sso_user'
    password: 'sso_pass'
    database: 'sso_db'
    driver: 'postgres'

logger:
  level: "info"
  file: "out.log"

